services:
  gateway:
    build: ./services/gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - user
      - game
      - chat
  
  auth:
    build: ./services/auth-service
    ports:
    - "3001:3000"
    env_file:
      - ./services/auth-service/.env
    volumes:
      - auth-db-data:/app/data
  user:
    build: ./services/user-service
    volumes:
      - user-db-data:/app/data

  game:
    build: ./services/game-service
    volumes:
      - game-db-data:/app/data
    
  chat:
    build: ./services/chat-service
    volumes:
      - chat-db-data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

volumes:
    auth-db-data:
    user-db-data:
    game-db-data:
    chat-db-data:
